version: "3"
services:
  # Postgresql database where the Data Warehouse is implemented
  warehouse:
    image: postgres:11
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: warehouse_db
    volumes:
      - ./private/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # Web app to interface more comfortably with the warehouse
  adminer:
    image: adminer:4.7
    depends_on:
      - warehouse
    ports:
      - 8080:8080

  # Jupyter server
  jupyter:
    image: jupyter
    build: ./jupyter
    depends_on:
      - warehouse
    ports:
      - 8888:8888
    volumes:
      - ./jupyter/notebooks:/notebooks
    environment:
      CONNECTION_STRING: "postgresql://user:pass@warehouse:5432/warehouse_db"

  # API that connects to the warehouse and allows retrieving information as well
  # as make forecasts
  api:
    image: api
    build: ./api
    depends_on:
      - warehouse
    restart: always
    ports:
      - 5000:5000
    volumes:
      - ./api:/home/api
    environment:
      CONNECTION_STRING: "postgresql://user:pass@warehouse:5432/warehouse_db"
