version: "3"
services:
  # Postgresql database where the Data Warehouse is implemented
  warehouse:
    image: postgres:11
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: warehouse_db
    volumes:
      - ./private/postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  # Web app to interface more comfortably with the warehouse
  adminer:
    image: adminer:4.7
    ports:
      - 8080:8080
