name: data_loader
channels:
  - conda-forge
  - defaults
dependencies:
  - autopep8=1.4.4
  - pip=19.1
  - psycopg2=2.7.6.1
  - python=3.6.7
  - numpy=1.16.4
  - pandas=0.24.2
  - sqlalchemy=1.3.4
  - sqlite=3.28.0
