name: jupyter
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyter=1.0.0
  - pip=19.1
  - psycopg2=2.7.6.1
  - python=3.6.7
  - matplotlib=3.1.0
  - numpy=1.16.4
  - pandas=0.24.2
  - seaborn=0.9.0
  - sqlalchemy=1.3.4
